export interface MediaPublication {
  name: string
  categories: string[]
  domain: string // used for Clearbit logo API
}

export const MEDIA_PUBLICATIONS: MediaPublication[] = [
  // Tier 1
  { name: 'Forbes', categories: ['BUSINESS', 'FINANCE'], domain: 'forbes.com' },
  { name: 'Vanity Fair', categories: ['LIFESTYLE', 'FASHION'], domain: 'vanityfair.com' },
  { name: 'Fast Company', categories: ['BUSINESS', 'TECH'], domain: 'fastcompany.com' },
  { name: 'The Luxury Playbook', categories: ['LIFESTYLE', 'REAL ESTATE', 'FINANCE'], domain: 'theluxuryplaybook.com' },
  { name: 'Entrepreneur', categories: ['BUSINESS'], domain: 'entrepreneur.com' },
  { name: 'Business Insider', categories: ['BUSINESS', 'FINANCE', 'TECH'], domain: 'businessinsider.com' },
  { name: 'Associated Press', categories: ['BUSINESS'], domain: 'apnews.com' },
  { name: 'USA Today', categories: ['BUSINESS', 'LIFESTYLE'], domain: 'usatoday.com' },
  { name: 'VentureBeat', categories: ['TECH'], domain: 'venturebeat.com' },
  { name: 'Benzinga', categories: ['FINANCE'], domain: 'benzinga.com' },
  { name: 'Variety', categories: ['ENTERTAINMENT'], domain: 'variety.com' },
  { name: 'International Business Times', categories: ['BUSINESS', 'FINANCE'], domain: 'ibtimes.com' },
  { name: 'GQ', categories: ['FASHION', 'LIFESTYLE'], domain: 'gq.com' },
  { name: 'Daily Mail', categories: ['LIFESTYLE'], domain: 'dailymail.co.uk' },
  { name: 'Vogue', categories: ['FASHION'], domain: 'vogue.com' },
  { name: 'Mashable', categories: ['TECH', 'LIFESTYLE'], domain: 'mashable.com' },
  { name: 'LA Weekly', categories: ['ENTERTAINMENT', 'LIFESTYLE'], domain: 'laweekly.com' },
  { name: "Harper's Bazaar", categories: ['FASHION'], domain: 'harpersbazaar.com' },
  { name: 'Village Voice', categories: ['ENTERTAINMENT', 'LIFESTYLE'], domain: 'villagevoice.com' },
  { name: 'Financial Times', categories: ['FINANCE', 'BUSINESS'], domain: 'ft.com' },
  { name: 'Washington Times', categories: ['BUSINESS'], domain: 'washingtontimes.com' },
  { name: 'Esquire', categories: ['FASHION', 'LIFESTYLE'], domain: 'esquire.com' },
  { name: 'Smart Company', categories: ['BUSINESS', 'TECH'], domain: 'smartcompany.com.au' },
  { name: 'Digital Journal', categories: ['TECH', 'BUSINESS'], domain: 'digitaljournal.com' },
  { name: 'Apple News', categories: ['TECH'], domain: 'apple.com' },
  { name: 'CEO Weekly', categories: ['BUSINESS'], domain: 'ceoweekly.com' },
  { name: 'New York Weekly', categories: ['BUSINESS', 'LIFESTYLE'], domain: 'newyorkweekly.com' },
  { name: 'Economic Insider', categories: ['FINANCE', 'BUSINESS'], domain: 'economicinsider.com' },
  { name: 'HackerNoon', categories: ['TECH', 'WEB 3'], domain: 'hackernoon.com' },
  { name: 'Tech Times', categories: ['TECH'], domain: 'techtimes.com' },
  { name: 'Madison Graph', categories: ['BUSINESS'], domain: 'madisongraph.com' },
  { name: 'US Reporter', categories: ['BUSINESS'], domain: 'usreporter.com' },
  { name: 'The Ritz Herald', categories: ['BUSINESS', 'LIFESTYLE'], domain: 'ritzherald.com' },
  { name: 'Medium', categories: ['TECH', 'BUSINESS'], domain: 'medium.com' },
  { name: 'Metro.co.uk', categories: ['LIFESTYLE'], domain: 'metro.co.uk' },
  { name: 'Tech Bullion', categories: ['TECH', 'FINANCE'], domain: 'techbullion.com' },
  { name: 'Luxury Lifestyle Magazine', categories: ['LIFESTYLE', 'FASHION'], domain: 'luxurylifestylemag.co.uk' },
  { name: 'The Source', categories: ['ENTERTAINMENT'], domain: 'thesource.com' },
  { name: 'Billboard', categories: ['ENTERTAINMENT'], domain: 'billboard.com' },
  { name: 'Your EDM', categories: ['ENTERTAINMENT'], domain: 'youredm.com' },
  { name: 'Analytics Insight', categories: ['TECH'], domain: 'analyticsinsight.net' },
  { name: 'GeekExtreme', categories: ['TECH'], domain: 'geekextreme.com' },
  { name: 'The Wall Street Times', categories: ['FINANCE', 'BUSINESS'], domain: 'thewallstreettimes.com' },
  { name: 'NewsMax', categories: ['BUSINESS'], domain: 'newsmax.com' },
  { name: 'LiveMint', categories: ['FINANCE', 'BUSINESS'], domain: 'livemint.com' },
  { name: 'Cyprus Mail', categories: ['BUSINESS'], domain: 'cyprus-mail.com' },
  { name: 'Portugal News', categories: ['BUSINESS'], domain: 'theportugalnews.com' },
  { name: 'Jerusalem Post', categories: ['BUSINESS'], domain: 'jpost.com' },
  { name: 'The Guardian', categories: ['BUSINESS', 'LIFESTYLE'], domain: 'theguardian.com' },
  { name: 'Globe and Mail', categories: ['BUSINESS', 'FINANCE'], domain: 'theglobeandmail.com' },
  { name: 'Daily Caller', categories: ['BUSINESS'], domain: 'dailycaller.com' },
  { name: 'Chicago Tribune', categories: ['BUSINESS'], domain: 'chicagotribune.com' },
  { name: 'Daily Record', categories: ['LIFESTYLE'], domain: 'dailyrecord.co.uk' },
  { name: 'Toronto Star', categories: ['BUSINESS'], domain: 'thestar.com' },
  { name: 'Manchester Evening News', categories: ['LIFESTYLE'], domain: 'manchestereveningnews.co.uk' },
  { name: 'Deadline', categories: ['ENTERTAINMENT'], domain: 'deadline.com' },
  { name: 'Khaleej Times', categories: ['BUSINESS', 'FINANCE'], domain: 'khaleejtimes.com' },
  { name: 'Gulf Times', categories: ['BUSINESS'], domain: 'gulf-times.com' },
  { name: 'NewsBTC', categories: ['WEB 3', 'FINANCE'], domain: 'newsbtc.com' },
  { name: 'Gulf News', categories: ['BUSINESS'], domain: 'gulfnews.com' },
  { name: 'AsiaOne', categories: ['BUSINESS'], domain: 'asiaone.com' },
  { name: 'Herald Sun', categories: ['BUSINESS'], domain: 'heraldsun.com.au' },
  { name: 'Fox', categories: ['BUSINESS', 'ENTERTAINMENT'], domain: 'foxnews.com' },
  { name: 'Grit Daily', categories: ['TECH', 'BUSINESS'], domain: 'gritdaily.com' },
  { name: 'Tech Cabal', categories: ['TECH'], domain: 'techcabal.com' },
  { name: 'Financial Tech Times', categories: ['FINANCE', 'TECH'], domain: 'financialtechtimes.com' },
  { name: 'Markets Herald', categories: ['FINANCE'], domain: 'marketsherald.com' },
  { name: 'Fox Interviewer', categories: ['BUSINESS', 'ENTERTAINMENT'], domain: 'foxinterviewer.com' },
  { name: 'Artist Weekly', categories: ['ENTERTAINMENT'], domain: 'artistweekly.com' },
  { name: 'US Business News', categories: ['BUSINESS'], domain: 'usbusinessnews.com' },
  { name: 'World Reporter', categories: ['BUSINESS'], domain: 'worldreporter.com' },
  { name: 'Market Daily', categories: ['FINANCE', 'BUSINESS'], domain: 'marketdaily.com' },
  { name: 'Bigtime Daily', categories: ['BUSINESS'], domain: 'bigtimedaily.com' },
  { name: 'Global Banking & Finance', categories: ['FINANCE'], domain: 'globalbankingandfinance.com' },
  { name: 'London Insider', categories: ['BUSINESS', 'LIFESTYLE'], domain: 'londoninsider.co.uk' },
  { name: 'Saudi Gazette', categories: ['BUSINESS'], domain: 'saudigazette.com.sa' },
  { name: 'Finextra', categories: ['FINANCE', 'TECH'], domain: 'finextra.com' },
  { name: 'Tech Round', categories: ['TECH'], domain: 'techround.co.uk' },
  { name: 'Huff Mag', categories: ['LIFESTYLE'], domain: 'huffpost.com' },
  { name: 'Elle', categories: ['FASHION'], domain: 'elle.com' },
  { name: 'Marie Claire', categories: ['FASHION', 'LIFESTYLE'], domain: 'marieclaire.com' },
  { name: 'NY Wire', categories: ['BUSINESS'], domain: 'nywire.com' },
  { name: 'Entrepreneur Times', categories: ['BUSINESS'], domain: 'entrepreneurtimes.com' },
  { name: "Men's Health", categories: ['HEALTH', 'LIFESTYLE'], domain: 'menshealth.com' },
  { name: 'Scottish Daily Express', categories: ['LIFESTYLE'], domain: 'scottishdailyexpress.co.uk' },
  { name: 'Chronicle Live', categories: ['LIFESTYLE'], domain: 'chroniclelive.co.uk' },
  { name: 'Swagger Magazine', categories: ['FASHION', 'LIFESTYLE'], domain: 'swaggermagazine.com' },
  { name: 'Health Shots', categories: ['HEALTH'], domain: 'healthshots.com' },
  { name: 'Free Press Journal', categories: ['BUSINESS'], domain: 'freepressjournal.in' },
  { name: 'Telangana Today', categories: ['BUSINESS'], domain: 'telanganatoday.com' },
  { name: 'Lifestyle Daily UK', categories: ['LIFESTYLE'], domain: 'lifestyledaily.co.uk' },
  { name: 'Cultr', categories: ['LIFESTYLE', 'ENTERTAINMENT'], domain: 'cultr.com' },
  { name: 'BLK News', categories: ['BUSINESS'], domain: 'blknews.com' },
  { name: 'The Brag', categories: ['ENTERTAINMENT'], domain: 'thebrag.com' },
  { name: "Women's Journal", categories: ['LIFESTYLE', 'FASHION'], domain: 'womensjournal.com' },
  { name: 'The Standard', categories: ['BUSINESS'], domain: 'thestandard.com' },
  { name: 'The Advocate', categories: ['LIFESTYLE'], domain: 'theadvocate.com' },
  { name: 'Denver Gazette', categories: ['BUSINESS'], domain: 'denvergazette.com' },
]

export const MEDIA_CATEGORIES = [
  'ALL',
  'BUSINESS',
  'FINANCE',
  'TECH',
  'LIFESTYLE',
  'FASHION',
  'ENTERTAINMENT',
  'HEALTH',
  'REAL ESTATE',
  'WEB 3',
]
